default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: grand_order_development

test:
  <<: *default
  database: grand_order_test

production:
  <<: *default
  database: grand_order
